### ISSUE TITLE
Can you make this available for the new MyKi App?

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [ArtBIT/home-assistant-myki#1]
@ArtBIT I did set up the MYKI 4 Watch using the QR code on the box giving me the new app in Google App Store… but with the credentials of this app (email and password) I can not login to the web app … any suggestions?

**Comment by ArtBIT** [comment]
@smarthomefamilyverrips Hello. I am using username + password to login to the web app, not email + password. Have you tried that?

**Comment by smarthomefamilyverrips** [comment]
@ArtBIT At the new app you not have a username, you only are able to login with email, when I try to login with this on the web app it says wrong username or password

**Comment by ArtBIT** [comment]
@smarthomefamilyverrips ah I see. I am using this one https://play.google.com/store/apps/details?id=com.alterco.safewatch_kiddo

Maybe try contacting their support and ask how to login to their webapp?

**Comment by smarthomefamilyverrips** [comment]
@ArtBIT I did talk with support and it seems that my MyKi Watch 4 not is supported for the web app, what model MyKi watch you are using if I may ask?

**Comment by ArtBIT** [comment]
@smarthomefamilyverrips I have MyKi Touch, I'll double check the version when I get back home, but from here I can only check the API which only has the firmware version:
`G72F_V1(JT)_HW_1.00_2021.11.24_16.45.44`

**Comment by smarthomefamilyverrips** [comment]
@ArtBIT ok thank you!

**Comment by ArtBIT** [comment]
I will close this, since there's nothing I can do. MyKi does not offer API access for the newer devices.
