### ISSUE TITLE
Help with integration set-up

### ISSUE THREAD

**Issue by fulesfules** [ArtBIT/home-assistant-myki#2]
Hi, 
I tried to use your code in Home Assisstant, but I could not figure out what shell I enter the values in secrets.yaml. 
I thought the username + pass would be enoght, but I get an error back if these fields are blank:

```
`Logger:` homeassistant.components.rest.sensor
Source: components/rest/sensor.py:170
Integration: RESTful ([documentation](https://www.home-assistant.io/integrations/rest), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+rest%22))
First occurred: 2022. december 1. 08:25:39 (121 occurrences)
Last logged: 12:15:13
JSON result was not a dictionary or list with 0th element a dictionary

```
 Did I miss something? I can log in with username+pass on the linked Webpage.

**Comment by ArtBIT** [comment]
You can add the official `File Editor` add-on, and create `secrets.yaml` from there.
Alternatively, you can SSH into your HomeAssistant and create `/config/secrets.yaml`  from there.
But yeah, using raw auth should work. Just login to the myki website and in the console type `CWA.Ajax.auth` hit enter, copy the result, and replace:
```
Authorization: !secret my_myki_token
```
With:
```
Authorization: Basic THE_RESULT_OF_CWA_AJAX_AUTH
```

**Comment by fulesfules** [comment]
Hmm, ok, I can do it, but why do we need the login + password?

**Comment by fulesfules** [comment]
Another question: Can it differentiate between two watches linked to the same account? How? (the first one was buggy, so I have now a second one, which is the only active one)

**Comment by ArtBIT** [comment]
> Hmm, ok, I can do it, but why do we need the login + password?

You only need the username + password to login to MyKi website and get the Authorization code (and store it in you `secrets.yaml` file or hardocde it in the rest sensor). After that, Home Assistant will send the authorization code in the Authorization header with each and every request to MyKi servers to fetch the data.

**Comment by ArtBIT** [comment]
> Another question: Can it differentiate between two watches linked to the same account? How? (the first one was buggy, so I have now a second one, which is the only active one)

See the [Readme.md](/ArtBIT/home-assistant-myki/blob/main/README.md) and look for the following lines:
```
# ... repeat for any other devices
```

1. You need to define a new device in `known_devices.yaml`
2. You need to define a new rest sensor in `packages/myki.yaml` and change the deviceid param: `id: !secret my_myki_device` (You don't need to use the `secrets.yaml`, you can hard-code the values)
3. You need to define a new automation in `packages/myki.yaml` just rename the `sensor.myki_watch_1` entity with your new entity id.

**Comment by fulesfules** [comment]
Hey, thanks for the quick answers! And let me thank you for this integration, I was very happy as I found it.
Actually I have only onw working watch, so I just want the REST API to report on my second watch.
Which I was missing maybe, that secrets.yaml I had just a blank string defined for my_myki_device. Now I suppode to enter here the ten digit id of the watch, right?

**Comment by fulesfules** [comment]
Perfect, many thanks, it works now. It updates its values. The only thing I have to figure out, why it doesn't show up on the general map tile. But it has nothing to do with this superb integration.

**Comment by ArtBIT** [comment]
> I suppose to enter here the ten digit id of the watch, right?

Yeah the deviceid is the unique 10 digit identifier for the device.

> The only thing I have to figure out, why it doesn't show up on the general map tile

Create a new person and set the newly created MyKi device as a tracking device.

> thank you for this integration

It's not really an integration, it's more of a hack, but you're welcome. I had a hard time finding a solution for this, so I've decided to share my setup.

> it works now

Great! I will close this issue as resolved, then.

Cheers
